# Generated by Django 4.1.1 on 2022-10-04 03:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_account_first_name_remove_account_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_img',
            field=models.ImageField(default='profile_images/logo-only-nobg.png', upload_to='profile_images/'),
        ),
    ]
