# Generated by Django 4.1.1 on 2022-09-30 21:25

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=15)),
                ('hashtag', models.CharField(max_length=50)),
                ('text_post', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image_post', models.ImageField(blank=True, null=True, upload_to='base/static/images/post/')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
