# Generated by Django 4.1.1 on 2022-10-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_rename_text_post_addpost_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
