# Generated by Django 4.1.1 on 2022-10-05 05:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_addpost_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpost',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
