# Generated by Django 4.1.1 on 2022-10-05 05:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_profile_img_account_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
