# Generated by Django 4.1.1 on 2022-10-23 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_rename_friends_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user',
        ),
        migrations.AddField(
            model_name='account',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friend',
            name='reciever',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='users.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friend',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='users.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friend',
            name='status',
            field=models.CharField(blank=True, choices=[('request', 'request'), ('send', 'send'), ('accepted', 'accepted')], default='request', max_length=8),
        ),
    ]
