# Generated by Django 4.1.1 on 2022-10-23 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_friend_friends_remove_friend_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='friends',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
