# Generated by Django 4.1.1 on 2022-10-23 03:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_friend'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friend',
            new_name='Relationship',
        ),
    ]
