# Generated by Django 4.1.1 on 2022-10-24 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_friend_relationship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
