# Generated by Django 4.1.1 on 2022-10-24 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_account_folowings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='folowings',
            new_name='followings',
        ),
    ]
