# Generated by Django 4.1.1 on 2022-10-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_remove_addpost_likes_addpost_likes'),
        ('users', '0018_account_friends_delete_friendlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='posts_liked',
            field=models.ManyToManyField(blank=True, related_name='posts_liked', to='post.addpost'),
        ),
    ]
