# Generated by Django 4.1.1 on 2022-09-30 22:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_rename_posts_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='AddPost',
        ),
    ]
