# Generated by Django 4.1.1 on 2022-09-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_post_addpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addpost',
            old_name='text_post',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='addpost',
            old_name='image_post',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='addpost',
            old_name='header',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='addpost',
            name='hashtag',
        ),
        migrations.AddField(
            model_name='addpost',
            name='hashtags',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
