# Generated by Django 4.1.1 on 2022-10-05 05:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_addpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpost',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, default='Hi!', null=True),
        ),
    ]
