# Generated by Django 4.1.1 on 2022-10-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_addpost_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpost',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
