# Generated by Django 4.1.1 on 2022-10-27 01:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0019_account_posts_liked'),
        ('post', '0011_remove_addpost_likes_addpost_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddPost',
            new_name='Post',
        ),
    ]
